config/routes.rb
Rails.application.routes.draw do
  resources :follows

  devise_for :users, controllers: { registrations: 'registrations' }

  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  resources :users, only: [:show]

  resources :posts do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]

    member do
      put 'like' => 'posts#like'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'

  validates :follower_id, uniqueness: { scope: :followee_id }
  validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  include ImageUploader::Attachment(:image)
  has_many :comments, dependent: :destroy
  validates :content, presence: true, length: { maximum: 200 }
  after_save :update_post_count

  after_save :update_cached_votes_total

  acts_as_votable

  private

  def update_cached_votes_total
    update_column(:cached_votes_total, votes_for.size)
  end

  def update_post_count
    user.update_attribute(:posts_counter, user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy, foreign_key: 'user_id'
  has_many :comments, dependent: :destroy, foreign_key: 'user_id'
  has_many :likes, dependent: :destroy, foreign_key: 'user_id'

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  acts_as_voter

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  include ImageUploader.Attachment(:image)

  validates :name, presence: true, length: { maximum: 20 }
  validates :bio, length: { maximum: 200 }

  def self.suggest_users(user)
    user = users.reject { |u| following.include?(u) }.reject { |u| u == user }
  end

  def following?(user)
    followees.include?(user)
  end

  def followers_counter
    followers.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name username avatar bio current_password image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
    else
      flash[:alert] = 'Comment was failed to create.'
    end
    redirect_to post_path(@comment.post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # def index
  #   @users = User.all
  #   @user = User.new
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js, :html, :json

  before_action :authenticate_user!
  before_action :find_post, only: [:show]

  def index
    @users = User.includes(:posts).all.order(created_at: :desc)
    @user = current_user
    @posts = Post.all.order('created_at DESC')
  end

  def like
    @post = Post.find(params[:id])
    case params[:format]
    when 'like'
      @post.liked_by current_user
      flash[:notice] = 'You liked this post'
    when 'unlike'
      @post.unliked_by current_user
      flash[:notice] = 'You unliked this post'
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    redirect_to user_path(current_user) if @post.save
    # if @post.save
    #   params[:images]&.each { |img| @post.photos.create(image: img) }
    #   redirect_to posts_path
    #   flash[:notice] = 'Saved ...'
    # else
    #   flash[:alert] = 'Something went wrong ...'
    #   redirect_to posts_path
    # end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]
    return if @post

    flash[:danger] = 'Post not exist!'
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :content, :image
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def follow
    @user = User.find(params[:id])
    current_user.followees << @user
    redirect_back(fallback_location: user_path(@user))
    flash[:notice] = "You are now following #{@user.username}"
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.followed_users.find_by(followee_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
    flash[:notice] = "You are no longer following #{@user.username}"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    user.image_url || 'img/user.png'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_with(model: Comment.new, url: post_comments_path(post)) do |f| %>
  <%= f.text_field :content, class: "form-control border-0", placeholder: "Add a comment" %>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the Instagram clone!</h1>
<!-- rediret to sign up if there are no users -->
<% if @users.empty? %>
  <%= link_to 'Sign up', new_user_session_path %>
<% else %>
  <h1>User already signed in!</h1>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="header">
  <div class="header-container">
    <!-- LOGO -->
    <%= link_to root_path do %> <%= image_tag 'img/nav-logo.png', alt: 'Instagram logo', class: 'logo'%> <% end %>
    <div class="navigation">
      <!-- SEARCHBAR -->
      <form class="searchbar">
        <!-- LOGO -->
        <label> <ion-icon class="search-icon" name="search-outline"></ion-icon> </label>
        <input class="search-input" placeholder="Search" />
      </form>
      <!-- NAVBAR -->
      <nav class="main-nav">
        <ul class="main-nav-list">
          <li class="main-nav-link">
            <% if current_user %> <%= link_to root_path, class: 'nav-link' do %> <ion-icon name="home-outline"></ion-icon>
            <% end %> <% end %>
          </li>
          <li class="main-nav-link">
            <ion-icon name="paper-plane-outline"></ion-icon>
          </li>
          <li class="main-nav-link">
            <!-- link to posts/new -->
            <% if current_user %> <%= link_to new_post_path, class: 'nav-link' do %> <ion-icon name="add-outline" class="add-nav-btn"></ion-icon> <% end %> <% end %>
            <!-- <ion-icon name="add-outline" class="add-nav-btn"></ion-icon> -->
          </li>
          <li class="main-nav-link">
            <ion-icon name="compass-outline"></ion-icon>
          </li>
          <li class="main-nav-link">
            <ion-icon name="heart-outline"></ion-icon>
          </li>
          <li class="main-nav-link">
            <%= link_to user_path(current_user), class: 'profile-img' do %> 
            <% if current_user %>
             <%= image_tag avatar_url(current_user), class: 'profile-img' %> <% else %>
            <ion-icon name="person-circle-outline" class="profile-img"></ion-icon>
            <% end %> <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>

  <div class="header--mobile__container">
    <% if current_user %> <%= link_to new_post_path, class: 'nav-link' do %> <ion-icon name="add-outline" class="add-nav-btn"></ion-icon> <% end %> <% end %> <%= link_to root_path do %> <%= image_tag 'img/nav-logo.png', alt: 'Instagram logo', class: 'logo'%> <% end %>
    <ion-icon name="person-add-outline" class="add-person-nav-btn"></ion-icon>
  </div>
</header>

<nav class="mobile--navbar">
  <%= link_to root_path, class: 'mobile--nav__icon' do %>
  <ion-icon class="mobile--nav__icon" name="home"></ion-icon>
  <% end %>
  <ion-icon class="mobile--nav__icon" name="search-outline"></ion-icon>
  <% if current_user %> <%= link_to new_post_path, class: 'nav-link' do %> <ion-icon name="add-outline" class="add-nav-btn"></ion-icon> <% end %> <% end %> <%= link_to user_path(current_user), class: 'profile-img' do %> <% if current_user %> <%= image_tag avatar_url(current_user), class: 'profile-img' %> <% else %>
  <ion-icon name="person-circle-outline" class="profile-img"></ion-icon>
  <% end %> <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
  </head>

  <body>
    <%= render 'layouts/navbar' if current_user %> 
    <% if notice %>
    <p class="notice">
      <ion-icon class="alert--icon" name="checkmark-done-outline"></ion-icon>
      <%= notice %>
    </p>
    <% end %>
    <% if alert %>
    <p class="alert">
      <ion-icon class="alert--icon" name="alert-circle-outline"></ion-icon>
      <%= alert %>
    </p>
    <% end %> <%= yield %>
    <footer class="footer">
      <div class="footer-links">
        <a href="https://instagram.com/about/legal/privacy/">Privacy</a>
        <a href="https://instagram.com/about/legal/terms/">Terms</a>
        <a href="https://instagram.com/about/legal/cookies/">Cookies</a>
        <a href="https://instagram.com/about/legal/community_guidelines/">Guidelines</a>
        <a href="https://instagram.com/about/legal/dmca/">DMCA</a>
        <a href="https://instagram.com/about/legal/">Legal</a>
        <a href="https://instagram.com/about/">About</a>
        <a href="https://instagram.com/about/jobs/">Jobs</a>
        <a href="https://instagram.com/about/help/">Help</a>
        <a href="https://instagram.com/about/api/">API</a>
        <a href="https://instagram.com/about/top_accounts/">Top Accounts</a>
        <a href="https://instagram.com/about/hashtags/">Hashtags</a>
        <a href="https://instagram.com/about/locations/">Locations</a>
        <a href="https://instagram.com/about/instagram_lite/">Instagram Lite</a>
      </div>
      <p>© 2021 Instagram from Rustamjon@Maqsud</p>
    </footer>

    <!-- ION iCONS -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/posts/index.html.erb
<section class="main">
  <div class="container">
    <div class="main-bar">
      <div>
        <ul class="stories-list">
          <% @users.each do |user| %>
          <li class="stories-link">
            <%= link_to user_path(user) do %>
            <%= image_tag avatar_url(user), class: "story-profile-img" %>
            <% end %>
            <p class="story-profile-name"><%= user.name %></p>
          </li>
          <% end %>
        </ul>
      </div>

      <!-- MAIN SECTION -->
      <% @posts.each do |post| %>
      <div class="post">
        <div class="post-top-bar">
          <div class="post__profile--info">
            <%= link_to user_path(post.user) do %> <%= image_tag avatar_url(post.user), class: "post__profile--img" %> <% end %>
            <div class="post__profile--name">
              <p class="profile--name"><%= link_to post.user.name, user_path(post.user), class: "username" %></p>
            </div>
          </div>
          <div class="post__profile--options">
            <ion-icon name="ellipsis-horizontal"></ion-icon>
          </div>
        </div>

        <%= link_to post_path(post), class: "post__img" do %> <%= image_tag post.image_url, class: "post--img" %> <% end %>

        <div class="post__bottom--bar">
          <div class="post__icons">
            <!-- like -->
            <% if current_user.liked? post %> <%= link_to like_post_path(post, 'unlike'), class: 'preached-btn', method: :put, remote: :true do %> ❤️ <% end %> <% else %> <%= link_to like_post_path(post, 'like'), class: 'preach-btn', method: :put, remote: :true do %> <ion-icon name="heart-outline"></ion-icon> <% end %> <% end %>

            <!-- comment -->
            <%= link_to post_path(post) do %>
            <ion-icon name="chatbubble-outline"></ion-icon>
            <% end %>
            <!-- telegraf -->
            <ion-icon name="paper-plane-outline"></ion-icon>
          </div>

          <div class="dots">...</div>

          <div class="post__icon--save">
            <ion-icon name="bookmark-outline"> </ion-icon>
          </div>
        </div>

        <div class="post--info">
          <span class="like_count" <%="post.id" %>><%= post.get_likes.size %> likes</span>

          <div class="post__full--info"><%= post.user.name %> <span class="more"><%= post.content %></span></div>
          <%= link_to post_path(post), class: "post__view--comments" do %> View all <%= post.comments.size %> comments <% end %>
          <div class="post__posted--time"><%= time_ago_in_words(post.created_at) %> AGO</div>
        </div>

        <%= form_with(model: Comment.new, url: post_comments_path(post), class: 'post__comments') do |f| %>
        <ion-icon class="comment__icon" name="happy-outline"></ion-icon>
        <%= f.text_field :content, class: "post__comment--input", placeholder: "Add a comment..." %> <%= f.submit "Post", class: "comment__submit" %> <% end %>
      </div>
      <% end %>
    </div>

    <!-- LEFT SIDEBAR -->
    <div class="side-bar">
      <div class="user__profile">
        <%= link_to user_path(current_user) do %>
        <%= image_tag avatar_url(@user), class: "user__img" %>
        <% end %>
        <div class="user__info">
          <p class="user__name"><%= link_to @user.name, user_path(@user) %></p>
          <p class="user__fullname"><%= @user.username %></p>
        </div>
        <a href="#" class="switch">Switch</a>
      </div>

      <div class="suggestions">
        <div class="suggestion__title">
          <p>Suggestions For You</p>
          <a class="see__all" href="#">See All</a>
        </div>

        <!--   suggest users that are not current and not following  -->
        <% @users.each do |user| %> <% unless user == current_user %> <% unless current_user.following? user %>
        <div class="sugessted__profile">
          <%= image_tag avatar_url(user), class: "sugessted__profile--img" %>
          <div class="user__info">
            <p class="user__name"><%= link_to user.name, user_path(user), class: "username" %></p>
            <p class="suggested__user__fullname"><%= user.username %></p>
          </div>
          <%= link_to "Follow", follow_user_path(user), method: :post, remote: :true, class: "switch" %>
        </div>
        <% end %> <% end %> <% end %>
      </div>

      <!-- FOOTER -->
      <div class="footer">
        <ul class="footer__list">
          <li class="footer__link">
            <a href="#">About</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Help</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Press</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">API</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Jobs</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Privacy</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Terms</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Language</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Top Accounts</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Hashtags</a>
          </li>
          <span>.</span>
          <li class="footer__link">
            <a href="#">Language</a>
          </li>
        </ul>
        <div class="copyright">© 2022 INSTAGRAM FROM META</div>
      </div>
    </div>
  </div>
</section>

app/views/posts/like.js.erb
$('.preached-btn').on('ajax:success', function() {
  $(this).parent().parent().find('.like_count')
  .html('<%= @post.get_likes.size %> likes');
  $(this).closest('.preached-btn').html('💔');
})            

$('.preach-btn').on('ajax:success', function() {
  $(this).parent().parent().find('.like_count')
  .html('<%= @post.get_likes.size %> likes');
  $(this).closest('.preach-btn').html('♥️');
})

app/views/posts/show.html.erb
<div class="container">
  <div class="popup" id="popup">
    <%= link_to :back if current_user do %>
    <ion-icon name="close-outline" class="close--post"></ion-icon>
    <% end %>

    <div class="popup-box">
      <div class="popup-img">
        <% if @post.present? %> <%= image_tag @post.image_url, class: "popup-img-preview" %>

        <% else %>
        <span class="profile--posts__img">
          <ion-icon name="alert-circle-outline" class="profile--posts__icon"></ion-icon>
          <p class="profile--error__title">TOO LARGE >> 2MB!</p>
          <p class="profile--error">Please upload a smaller file</p>
          <%= button_to "DELETE", post_path(@post), method: :delete, class: "profile--broken__link" %>
        </span>
        <% end %>
      </div>

      <div class="popup-content">
        <div class="popup-user">
          <div class="popup-profile-pic"><%= image_tag avatar_url(@post.user), class: "avatar" %></div>
          <div class="popup-username"><%= link_to @post.user.name, user_path(@post.user), class: "username" %></div>

      <% if current_user == @post.user %>
                  <%= button_to post_path(@post), method: :delete, class: "delete--post", data: {confirm: "Are you sure you want to delete this post?"} do %>
                  <ion-icon class="delete--post-ion-icon" name="trash-outline"></ion-icon> DELETE
                  <% end %>
                  <% end %>

          <%= link_to root_path, class: "popup-options" do %>
          <ion-icon name="chevron-back-outline" class="popup-options"></ion-icon>
          <% end %>
        </div>

        <% @post.comments.each do |comment| %>
        <div class="popup-comment">
          <%= image_tag avatar_url(comment.user), class: "avatar" %>
          <div class="popup-comment-content">
            <p class="popup-comment-user"><%= comment.user.name %></p>
            <p class="popup-comment-text"><%= comment.content %></p>
          </div>
        </div>
        <% end %> <%= form_with(model: Comment.new, url: post_comments_path(@post), class: 'post__comments popup__comments') do |f| %>
        <ion-icon class="comment__icon" name="happy-outline"></ion-icon>
        <%= f.text_field :content, class: "post__comment--input", placeholder: "Add a comment..." %> <%= f.submit "Post", class: "comment__submit" %> <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="section--profile container">
  <div class="profile--header">
    <%= image_tag avatar_url(@user), class: "profile--header__img" %>
    <div class="profile--info">
      <!-- username, edit-profile, settings-btn -->
      <div class="profile__name">
        <p class="profile__name--text"><%= @user.username %></p>
        <% if @user.id == current_user.id %> <%= link_to 'Edit Profile', edit_user_registration_path, class: 'profile--edit' %> <% elsif current_user.followees.include?(@user) %>
        <h5><%= button_to "Unfollow", unfollow_user_path, method: "POST",class: 'profile--edit' %></h5>
        <% else %>
        <h5><%= button_to "Follow", follow_user_path, method: "POST",class: 'profile--edit' %></h5>
        <% end%>
        <ion-icon class="profilo--settings" name="settings-outline"></ion-icon>
      </div>

      <!-- posts, followers, following -->
      <div class="profile__stats">
        <div class="stats--item">
          <p class="stats--item__number"><%= @user.posts.count %></p>
          <p class="stats--item__text">posts</p>
        </div>
        <div class="stats--item">
          <% if @user.followers_counter == 1 %>
          <p class="stats--item__number"><%= @user.followers.count %></p>
          <p class="stats--item__text">follower</p>
          <% else %>
          <p class="stats--item__number"><%= @user.followers.count %></p>
          <p class="stats--item__text">followers</p>
          <% end %>
        </div>
        <div class="stats--item">
          <% if @user.followees %>
          <p class="stats--item__number"><%= @user.followees.count %></p>
          <p class="stats--item__text">following</p>
          <% end %>
        </div>
      </div>

      <!-- fullname, bio -->
      <div class="profile--fullname">
        <p class="profile--fullname__text"><%= @user.name %></p>
        <p class="profile--fullname__bio"><%= @user.bio %></p>
      </div>
    </div>
  </div>

  <div class="profile--mobile--info">
    <p class="profile--fullname__text"><%= @user.name %></p>
    <p class="profile--fullname__bio"><%= @user.bio %></p>
  </div>

  <div class="profile--highlights">
    <!-- highlight--img, highlight--name -->
    <div class="highlights">
      <%= image_tag avatar_url(@user), class: "highlight--img" %>
      <p class="highlight--name"><%= @user.username %></p>
    </div>
  </div>

  <div class="profile--mobile__stats">
    <div class="stats--item">
      <p class="stats--item__number"><%= @user.posts.count %></p>
      <p class="stats--item__text">posts</p>
    </div>
    <div class="stats--item">
      <p class="stats--item__number"><%= @user.followers.count %></p>
      <p class="stats--item__text">followers</p>
    </div>
    <div class="stats--item">
      <p class="stats--item__number"><%= @user.followees.count %></p>
      <p class="stats--item__text">following</p>
    </div>
  </div>

  <div class="profile--posts__header">
    <ul class="posts--navbar">
      <!-- Posts, Videos, Saved, Tagged -->
      <li class="navbar--item">
        <ion-icon class="navbar--icon" name="images-outline"></ion-icon>
        <p class="navbar--text">Posts</p>
      </li>
      <li class="navbar--item">
        <ion-icon class="navbar--icon" name="images-outline"></ion-icon>
        <p class="navbar--text">Video</p>
      </li>
      <li class="navbar--item">
        <ion-icon class="navbar--icon" name="images-outline"></ion-icon>
        <p class="navbar--text">Saved</p>
      </li>
      <li class="navbar--item">
        <ion-icon class="navbar--icon" name="images-outline"></ion-icon>
        <p class="navbar--text">Tagged</p>
      </li>
    </ul>
  </div>

  <div class="profile--posts">
    <% @posts.each do |post| %> <%= link_to post_path(post) do %>
    <!-- standar_image -->
    <% if post != nil %> <%= image_tag post.image_url, class: "profile--posts__img" %> <% else %>
    <!-- put delete post button -->

    <span class="profile--posts__img">
      <ion-icon name="alert-circle-outline" class="profile--posts__icon"></ion-icon>
      <p class="profile--error__title">TOO LARGE >> 2MB!</p>
      <p class="profile--error">Please upload a smaller file</p>
      <%= button_to "Go to post link and DELETE", post_path(post), method: "DELETE", class: "profile--broken__link" %>
    </span>
    <% end %> <% end %> <% end %>
  </div>
</div>

<!-- explain the problem an your_project -->